site_name: Google Docs guide
nav:
  - About Google Docs: about-google-docs.md
  - Create document:
      - Create document in Google Docs: create-document/create-document.md 
      - Create document from Google Docs: create-document/from-google-docs.md
      - Create document from Google Drive: create-document/from-google-drive.md
      - Create document from File menu: create-document/from-file-menu.md
  - Download document: download-document.md
  - Print document: print-document.md
  - Manage access: manage-access.md
  - Manage page settings: manage-page-settings.md
  - Format text: format-text.md
  - Insert different types of content: 
      - Insert different types of content: insert-different-types-of-content/insert-different-types-of-content.md
      - Insert image: insert-different-types-of-content/insert-image.md
      - Insert table: insert-different-types-of-content/insert-table.md
      - Insert chart: insert-different-types-of-content/insert-chart.md
  - Manage add-ons: manage-add-ons.md

theme:
  name: material
  logo: image/Google_Docs_Logo_512px.png
  palette:
    primary: white
    accent: blue 
    scheme: defauit
  
  features:
    - navigation.indexes
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.footer 
    - content.tabs.link

markdown_extensions:
  - def_list
  - pymdownx.tasklist:
      custom_checkbox: true
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - attr_list
  - md_in_html
  - pymdownx.blocks.caption
  - sane_lists

extra_css:
  - stylesheets/extra.css
    
    

    